### ISSUE TITLE
Get Experimental Data broken

### ISSUE THREAD

**Issue by tdinelli** [edoardoramalli/SciExpeM_API#4]
Something is broken when performing the following operation:

from SciExpeM_API.SciExpeM import SciExpeM
my_sciexpem = SciExpeM(token='tokennnn')

e = my_sciexpem.filterDatabase(model_name = 'Experiment', id =2347)[0]

print(e.experimental_data)

**Comment by edoardoramalli** [comment]
For me it works

**Comment by tdinelli** [comment]
Solved in commit 74a64d5
